In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Ntu_Orders.csv')

In [3]:
df.head()

,SalesOrderSlaveId,DateId,MemberId,TradesOrderSlaveId,ShopId,SalePageId,TradesOrderGroupCode,TrackSourceTypeDef,TrackChannelTypeDef,TrackDeviceTypeDef,...,UnitPrice,PromotionDiscount,EcouponDiscount,SalesOrderSlaveTotalPayment,SalesOrderSlaveDateTime,SalesOrderSlaveStatusDef,PayProfileTypeDef,ShippingProfileTypeDef,EcouponId,IsSalePageGift
0,26914456,20170103,48D5DE26-236E-4854-8474-B0DCEAFF4F42,26971960,1317,9804,b'q\x14\xa49\xaa\\\xecs\xff6wH\xfbXd\x93\xfbf\...,Web,Brand,Mobile,...,399.0,-25.0,0.0,374.0,2017-01-03 23:11:47.207,Finish,SevenEleven,SevenEleven,NaN,False
1,26914457,20170103,48D5DE26-236E-4854-8474-B0DCEAFF4F42,26971961,1317,9804,b'q\x14\xa49\xaa\\\xecs\xff6wH\xfbXd\x93\xfbf\...,Web,Brand,Mobile,...,399.0,-25.0,0.0,374.0,2017-01-03 23:11:47.223,Finish,SevenEleven,SevenEleven,NaN,False
2,26767644,20170101,C8B989DB-05F9-42D3-BD4F-E203482C5E58,26825136,1317,10118,b'\x1d\x8f}\x12lu>.&\xfc\xbc\xe0\xd2\xad\xe5\x...,Web,Brand,Mobile,...,350.0,-34.0,0.0,316.0,2017-01-01 17:21:32.113,Finish,Family,Family,NaN,False
3,26780512,20170101,C39E36F7-5091-48DA-BE8F-8CE043E009EE,26837997,1317,10036,"b'&QI#u)\xf8\xf7\n6\x01~\xd1\xf3,\x1f\xb8\xe3\...",Web,Brand,Mobile,...,540.0,-57.0,0.0,483.0,2017-01-01 21:41:58.153,Finish,Family,Family,NaN,False
4,26823950,20170102,7D87099A-B49C-4136-A8E9-F76BB5588B19,26881442,1317,10268,b'\xfd\x0b\x9ee\xdc\xaea@\x102;jX\xfek\x99m\x1...,Web,Brand,Mobile,...,445.0,-44.0,0.0,401.0,2017-01-02 15:37:33.610,Finish,Family,Family,NaN,False

In [4]:
df.tail()

,SalesOrderSlaveId,DateId,MemberId,TradesOrderSlaveId,ShopId,SalePageId,TradesOrderGroupCode,TrackSourceTypeDef,TrackChannelTypeDef,TrackDeviceTypeDef,...,UnitPrice,PromotionDiscount,EcouponDiscount,SalesOrderSlaveTotalPayment,SalesOrderSlaveDateTime,SalesOrderSlaveStatusDef,PayProfileTypeDef,ShippingProfileTypeDef,EcouponId,IsSalePageGift
2268343,50056662,20171220,97E7CF33-3DF1-4514-AC5E-448D7DD41799,50120466,1317,16093,b'pG]\xcc\x00\xebp\xf8rh\xcc\xde\xf6\x9d\xf9\x...,AndroidApp,Brand,Mobile,...,199.0,0.0,0.0,199.0,2017-12-20 16:11:30.963,Finish,Family,Family,NaN,False
2268344,50056663,20171220,97E7CF33-3DF1-4514-AC5E-448D7DD41799,50120467,1317,16093,b'pG]\xcc\x00\xebp\xf8rh\xcc\xde\xf6\x9d\xf9\x...,AndroidApp,Brand,Mobile,...,199.0,0.0,0.0,199.0,2017-12-20 16:11:30.987,Finish,Family,Family,NaN,False
2268345,50057718,20171220,CEC073AD-FED6-4382-A408-56527B10DE4E,50121525,1317,9125,b'\xdd\xda\xe9\xbb\x12#\xe3\xca7\x0e\xb07\xff#...,Web,Brand,PC,...,249.0,0.0,0.0,249.0,2017-12-20 16:31:19.820,Cancel,Family,Family,NaN,False
2268346,50057719,20171220,CEC073AD-FED6-4382-A408-56527B10DE4E,50121526,1317,8602,b'\xdd\xda\xe9\xbb\x12#\xe3\xca7\x0e\xb07\xff#...,Web,Brand,PC,...,499.0,0.0,0.0,499.0,2017-12-20 16:31:19.840,Cancel,Family,Family,NaN,False
2268347,50058976,20171220,F135AC00-E702-47F1-B496-8EDCBE62EBBD,50122780,1317,10114,b'\xf4\n\x14\xdc\x85n\x17JY\x14\xb3\x99v\x15\x...,Web,Brand,PC,...,199.0,0.0,0.0,199.0,2017-12-20 16:54:19.263,Finish,SevenEleven,SevenEleven,NaN,False

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2268348 entries, 0 to 2268347
Data columns (total 27 columns):
SalesOrderSlaveId              int64
DateId                         int64
MemberId                       object
TradesOrderSlaveId             int64
ShopId                         int64
SalePageId                     int64
TradesOrderGroupCode           object
TrackSourceTypeDef             object
TrackChannelTypeDef            object
TrackDeviceTypeDef             object
LevelOneCategoryName           object
LevelTwoCategoryName           object
LevelThreeCategoryName         object
LevelFourCategoryName          object
IsMajor                        bool
IsGift                         bool
Quantity                       int64
UnitPrice                      float64
PromotionDiscount              float64
EcouponDiscount                float64
SalesOrderSlaveTotalPayment    float64
SalesOrderSlaveDateTime        object
SalesOrderSlaveStatusDef       object
PayProfileTypeDef              object
ShippingProfileTypeDef         object
EcouponId                      float64
IsSalePageGift                 bool
dtypes: bool(3), float64(5), int64(6), object(13)
memory usage: 421.8+ MB

In [6]:
df.shape

(2268348, 27)

In [7]:
df['new_DateId'] = pd.to_datetime(df['DateId'].astype(str), format='%Y%m%d')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2268348 entries, 0 to 2268347
Data columns (total 28 columns):
SalesOrderSlaveId              int64
DateId                         int64
MemberId                       object
TradesOrderSlaveId             int64
ShopId                         int64
SalePageId                     int64
TradesOrderGroupCode           object
TrackSourceTypeDef             object
TrackChannelTypeDef            object
TrackDeviceTypeDef             object
LevelOneCategoryName           object
LevelTwoCategoryName           object
LevelThreeCategoryName         object
LevelFourCategoryName          object
IsMajor                        bool
IsGift                         bool
Quantity                       int64
UnitPrice                      float64
PromotionDiscount              float64
EcouponDiscount                float64
SalesOrderSlaveTotalPayment    float64
SalesOrderSlaveDateTime        object
SalesOrderSlaveStatusDef       object
PayProfileTypeDef              object
ShippingProfileTypeDef         object
EcouponId                      float64
IsSalePageGift                 bool
new_DateId                     datetime64[ns]
dtypes: bool(3), datetime64[ns](1), float64(5), int64(6), object(13)
memory usage: 439.1+ MB

In [9]:
df.head()

,SalesOrderSlaveId,DateId,MemberId,TradesOrderSlaveId,ShopId,SalePageId,TradesOrderGroupCode,TrackSourceTypeDef,TrackChannelTypeDef,TrackDeviceTypeDef,...,PromotionDiscount,EcouponDiscount,SalesOrderSlaveTotalPayment,SalesOrderSlaveDateTime,SalesOrderSlaveStatusDef,PayProfileTypeDef,ShippingProfileTypeDef,EcouponId,IsSalePageGift,new_DateId
0,26914456,20170103,48D5DE26-236E-4854-8474-B0DCEAFF4F42,26971960,1317,9804,b'q\x14\xa49\xaa\\\xecs\xff6wH\xfbXd\x93\xfbf\...,Web,Brand,Mobile,...,-25.0,0.0,374.0,2017-01-03 23:11:47.207,Finish,SevenEleven,SevenEleven,NaN,False,2017-01-03
1,26914457,20170103,48D5DE26-236E-4854-8474-B0DCEAFF4F42,26971961,1317,9804,b'q\x14\xa49\xaa\\\xecs\xff6wH\xfbXd\x93\xfbf\...,Web,Brand,Mobile,...,-25.0,0.0,374.0,2017-01-03 23:11:47.223,Finish,SevenEleven,SevenEleven,NaN,False,2017-01-03
2,26767644,20170101,C8B989DB-05F9-42D3-BD4F-E203482C5E58,26825136,1317,10118,b'\x1d\x8f}\x12lu>.&\xfc\xbc\xe0\xd2\xad\xe5\x...,Web,Brand,Mobile,...,-34.0,0.0,316.0,2017-01-01 17:21:32.113,Finish,Family,Family,NaN,False,2017-01-01
3,26780512,20170101,C39E36F7-5091-48DA-BE8F-8CE043E009EE,26837997,1317,10036,"b'&QI#u)\xf8\xf7\n6\x01~\xd1\xf3,\x1f\xb8\xe3\...",Web,Brand,Mobile,...,-57.0,0.0,483.0,2017-01-01 21:41:58.153,Finish,Family,Family,NaN,False,2017-01-01
4,26823950,20170102,7D87099A-B49C-4136-A8E9-F76BB5588B19,26881442,1317,10268,b'\xfd\x0b\x9ee\xdc\xaea@\x102;jX\xfek\x99m\x1...,Web,Brand,Mobile,...,-44.0,0.0,401.0,2017-01-02 15:37:33.610,Finish,Family,Family,NaN,False,2017-01-02

In [10]:
df.loc[3] #by row

SalesOrderSlaveId                                                       26780512
DateId                                                                  20170101
MemberId                                    C39E36F7-5091-48DA-BE8F-8CE043E009EE
TradesOrderSlaveId                                                      26837997
ShopId                                                                      1317
SalePageId                                                                 10036
TradesOrderGroupCode           b'&QI#u)\xf8\xf7\n6\x01~\xd1\xf3,\x1f\xb8\xe3\...
TrackSourceTypeDef                                                           Web
TrackChannelTypeDef                                                        Brand
TrackDeviceTypeDef                                                        Mobile
LevelOneCategoryName                                                      服裝、內睡衣
LevelTwoCategoryName                                                          女裝
LevelThreeCategoryName                                                        上衣
LevelFourCategoryName                                                      成套衣褲組
IsMajor                                                                     True
IsGift                                                                     False
Quantity                                                                       1
UnitPrice                                                                    540
PromotionDiscount                                                            -57
EcouponDiscount                                                                0
SalesOrderSlaveTotalPayment                                                  483
SalesOrderSlaveDateTime                                  2017-01-01 21:41:58.153
SalesOrderSlaveStatusDef                                                  Finish
PayProfileTypeDef                                                         Family
ShippingProfileTypeDef                                                    Family
EcouponId                                                                    NaN
IsSalePageGift                                                             False
new_DateId                                                   2017-01-01 00:00:00
Name: 3, dtype: object

In [11]:
df['new_DateId'].head() #by column

0   2017-01-03
1   2017-01-03
2   2017-01-01
3   2017-01-01
4   2017-01-02
Name: new_DateId, dtype: datetime64[ns]

In [13]:
df.loc[1000:1005, 'Quantity'] #by [rows, cols]

TypeError: unhashable type: 'slice'

In [14]:
df.loc[1000:1005, ['new_DateId', 'Quantity']]

     new_DateId  Quantity
1000 2017-12-26         1
1001 2017-12-28         1
1002 2017-12-28         1
1003 2017-12-31         1
1004 2017-12-31         1
1005 2018-01-04         1

In [ ]:
df[df['Quantity'] > 1]